# Generated by Django 5.1 on 2024-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
    ]
