# Generated by Django 5.1 on 2024-08-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_doctor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='departmet',
            new_name='department',
        ),
    ]
