# Generated by Django 5.1 on 2024-08-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_departmet_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
